print("Array")
print("Ajit")
print(["movies","Games","Python"][0])
print(["movies","Games","Python"][2])
print("I like " + ["movies","Games","Python"][2])
print("I like " + ["movies","Games","Python"][1])
print("I like " + ["movies", "16", "Python"][1])
print("I like " + ["movies", str("16"), "Python"][1])
print("I like " + ["movies", "int(16)", "Python"][1])
