print("Hello Ajit")
print("My name is" + "Hello:Nick:World".split(":") [1])
print("raj")
print("This costs" +str(6)+"dollors")
print("This costs" +str("6+5")+"dollors")
print("This costs " + str(6+5) +" dollors")
print(("Hello:Nick:World").split(":"))
print("My name is"+"Hello:nick:world".split(":")[2])

print("My name is"+"Hello:nick:world".split(":")[0])
print("Hello:Nick:World".split(":"))
print(int(5.5))
print(str(5.5))
print(5+6)
print("5+6")
print("5" + "6")
print("This costs" +str(6+5)+"dollors")
print(int(5) + int(6))
print(int("5") + int("6"))
print(int(5.5)+int(4.5))
print(5.5+4.5)
print(int(5.5+4.5))
print(float(5.5))
print(float(int(5.5+4.5)))
print(float(str(int(5.5))))
print(int(float(5.5+4.5)))
print(float(int(5+9)))
print("Addition of two floatimg no.s is (int(5.5)+int(4.5))")